### ISSUE TITLE
[FEAT] Improve the Theme again

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/process-analytics.dev#110]
Once #22 is implemented

### Tasks

- [ ] when not on top, display a button to go back to the top. Users can already do it by clicking on the logo of the navbar, but this doesn't seem obvious
- [ ] footer: align the logo with the text
- [ ] logo: use 'white stroke' logo only with the navbar. When displayed with red background, use the regular one
- [ ] section height: too large when few content
- [ ] Down the link for Github & Twitter on the first section

**Comment by csouchet** [comment]
This issue was for the old theme. So, no need it anymore.
