### ISSUE TITLE
[FEAT] Limit the number of news/posts displayed in the home page

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/process-analytics.dev#187]
**Is your feature request related to a problem? Please describe.**
Currently, we display all posts/news in the home page.
We are going to have more and more content so we should only display the newest content.

**Describe the solution you'd like**
For now, we have no more than 6 elements. This seems to be enough for an highlight.
For extra content, we could create a dedicated page that list all of them and add a link to this page in the home page.
We could also introduce pagination in the new page right now or later when we will have dozen of elements to reference.

**Describe alternatives you've considered**
Do not change: we will progressively overload the page, especially if we don't implement #30.

**Tasks**

- [x] Create the blog page and dedicated menu #224
- [x] Propose a text as introduction of the blog page #226 
- [x] Add the more button on the blog home page section #225 
- [x] Create the news page #228
- [x] Propose a text as introduction of the news page #226 
- [x] Add the more button on the news home page section #229
- [x] Have no link for the **News** and **Blog** pages in the header of the **News** and **Blog** pages #292
- [x] Have a header and a footer in the **404** page #292

**Comment by csouchet** [comment]
It's a good idea to display only the 6 last elements from each sections and to have a link to the specific page with all the elements of a section 👍🏻

**Comment by csouchet** [comment]
Do something like the following for the new header to navigate to the different pages and their subsection:
 ![image](https://designspartan.com/wp-content/uploads/2021/04/40_Menus_navigation_responsives_beaux_efficaces_03.gif) 

### Home page
![image](https://user-images.githubusercontent.com/4921914/140954350-0c4ba1cc-ac63-44cc-b593-cf39ba3bfb4a.png)
- A pop-up appears on hover of the page **Home** in the header, and disappears else.
- We keep the red bar on hover on a page or a section on bottom. 
- The current page: We can add another red bar on bottom.

### Page subsection
![image](https://user-images.githubusercontent.com/4921914/140955232-b9d7bd2a-fba8-446f-9c26-0960b38a4a7d.png)
- We always display the header.
- We keep the red bar on hover on a page or a section on bottom. 
- Another behavior for the current page: We can color the title on red in order to make the difference between the current page and the next page.

**Comment by csouchet** [comment]
@NathalieC Could you give us feedbacks on my previous comment, when you have time ? 
Thanks 🙂

**Comment by tbouffard** [comment]
I suggest we start we a simple menu for the new pages, close to the one we have on the home page, but a different one.
We more urgently need a design for the news/posts list. We can work on the header later.

**Comment by csouchet** [comment]
### Proposition for the new Blog page
![image](https://user-images.githubusercontent.com/4921914/141149966-489f5dd9-1874-450e-a44e-1b423d467f0c.png)

**Comment by csouchet** [comment]
### Proposition for the Blog section
![image](https://user-images.githubusercontent.com/4921914/141823724-aac8d72e-da95-4389-b910-7bc1d6bc5d29.png)

**Comment by csouchet** [comment]
We decided to:
- have no link for the **News** and **Blog** pages in the header of the **News** and **Blog** pages
- have a **Back** button on the top left in the **News** and **Blog** pages
- have a header and a footer in the **404** page

**Comment by tbouffard** [comment]
Feedback will be managed with #568.
All tasks completed, so close the issue.
