### ISSUE TITLE
[FEAT] Improve the Theme

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/process-analytics.dev#22]
### Tasks

- [x] logo in the about section: set dimension for desktop and mobile. See #28
- [x] 404 page: set image dimension for desktop and mobile: #40 
- [x] Cards: add border to better highlight them as we are using a white background: #38 
- [x] Put complex diagram image on the Why sub-section #81
- [ ] Put monitoring image on second What sub-section #122
- [x] Change the icons in HelmetContent (for media): try to use the svg image directly. See #126 and  also #58 
- [x] use a smaller image for the "automated test" blog post (currently 1.7MB!). Better with #25.
- [x] logo: manage background color when displayed in the header and footer. See #24
