### ISSUE TITLE
[FEAT] Select a Theme

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/process-analytics.dev#4]
### Tasks

- [x] Merge the old **home** page & the new **home** page
- [x] Merge the old **404** page & the new **404** page
- [x] Replace the title of the **home** page
- [x] Replace the **About Me** section
- [x] Replace the color by Bonita color
- [x] Remove extra title when tippyjs popup is used: check accessibility when doing it
- [x] logo: use the svg file without png content
- [x] Rename the **Projects** section by something like **Tools** or **Libraries** (Change the related objects)
   - [x] Remove the logo @csouchet 
   - [x] Remove the published date @csouchet 
   - [x] Rename the **Homepage** link
- [x] Rename the **Writing** section by something like **Posts** (Change the related objects) @tbouffard 
   - [x] Replace fake content by the article for the 1st year of the BPMN Visualization librairie
   - [x] Replace fake content by the article for the one for the UID widget
   - [x] Replace fake content by the article for the one for the test visualization
- [x] Change the footer
   - [x] Add the name of the project & the logo
   - [x] add logo attribution in the footer
   - [x] Add link to https://github.com/EmaSuriano/gatsby-theme-mate 

### Resources
- the one we use in the poc: https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara
- https://www.gatsbyjs.com/plugins/gatsby-theme-blog/?=theme
- https://www.gatsbyjs.com/starters/?v=2h
- https://www.gatsbyjs.com/starters/gillkyle/gatsby-starter-landing-page
- https://www.gatsbyjs.com/starters/keegn/gatsby-starter-saas-marketing

**Comment by csouchet** [comment]
I don't know if we want to change the logo, but here, the different ressources found:
- [![image](https://user-images.githubusercontent.com/4921914/122783129-92456d80-d2b1-11eb-9011-d982c05e9d63.png)](https://www.flaticon.com/free-icon/technical-support_1835948?term=gear&related_id=1835948&origin=search)
- [![image](https://user-images.githubusercontent.com/4921914/122783040-8194f780-d2b1-11eb-96d5-6454c21c29e7.png)](https://thenounproject.com/term/chart/2039262/)
- [![image](https://user-images.githubusercontent.com/4921914/122782966-6fb35480-d2b1-11eb-9364-5747ae2bb7d2.png)](https://thenounproject.com/term/technology/1706444/)
- [![image](https://user-images.githubusercontent.com/4921914/122782752-4397d380-d2b1-11eb-80a8-af788b652b8f.png)](https://thenounproject.com/term/technology/2796034/)

**Comment by csouchet** [comment]
- https://www.gatsbyjs.com/plugins/@lekoarts/gatsby-theme-cara/?=gatsby-theme
   - https://themes.lekoarts.de/
   - https://specimens.lekoarts.de
- https://jodie.lekoarts.de/projects
- https://www.gatsbyjs.com/plugins/@narative/gatsby-theme-novela/?=gatsby-theme
-

**Comment by tbouffard** [comment]
For the footer, something like in a previous poc with more information

![image](https://user-images.githubusercontent.com/27200110/123059713-5671eb80-d40a-11eb-911d-4421e9d6ac97.png)
