### ISSUE TITLE
[INFRA] Replace style-components & rebass dependencies by Material UI

### ISSUE THREAD

**Issue by csouchet** [process-analytics/process-analytics.dev#831]
Remove the dependencies of `style-components`, `rebass`, and their associated TypeScript dependencies, while preserving the existing component design.

```[tasklist]
### Tasks
- [x] Header
- [x] Footer
- [x] Section #1116
- [x] Button #1103
- [x] Card
- [x] Divider #1098
- [x] SocialLink #1100
- [x] DescriptionPanel #1099
- [x] Gatsby config #1102
- [x] PostContainer #1106
- [x] PageWithPosts #1109
- [x] 404 page #1120
- [x] model-generation-application-conditions page #1113
- [x] model-generation-application page #1112
- [x] Landing section #1121
- [x] mailingListSubscription components #1123
- [ ] Layout #1134
- [x] model generation app components #1115
- [x] Mdx Panel & Image #1132
- [x] MDX render #1133
- [ ] remove dependencies #851
```
